### ISSUE TITLE
Recoding of cadres for individual data

### ISSUE THREAD

**Issue by grlurton** [grlurton/DRC_HRH#18]
RecodePost <- function(PostInit){
  PostInit[PostInit %in% c('administrateur' , 'administrateur_gestionnaire')] <- 'administrateur'

  PostInit[PostInit %in% c('autre' , 'Autre')] <- 'autre'

  PostInit[PostInit %in% c("membre_du_personnel" , "membre_personnel")] <- 'autre'

  PostInit[PostInit %in% c("technicien_labo" , "technicien_laboratoire")] <- 'labo'

  PostInit[PostInit %in%  c('infirmier' , 'infirmier_superviseur' , 
                            'infirmier_titulaire' , 'directeur_nursing')] <- 'infirmier'

  PostInit[PostInit %in% c("medecin" , "medecin_chef_staff" , "medecin_directeur" ,
                           "medecin_generaliste_specialiste")] <- 'medecin'
  PostInit
}

**Comment by mariapaola5** [comment]
@grlurton -- finally looked into this..
for FACILITY (not here, but in Drive/data/input_recode_staff), I think it may be better to leave the pharmacists in a specific category and put the "preposés à la pharmacie" with the nurses. This should impact the pletore/penurie graphs, only for HGR. OK? too much work? shall i/you add an "issue"?

For INDIVIDUAL questionnaire: the categories should be in the code  above. If I remember well, these come from questions on role/titre/poste in the facility.. All looks fine to me (just need to remember preposé is with labo/pharmaciste).

**Comment by grlurton** [comment]
@mariapaola5  Facility : nope, pretty straightforward

just to be clear, keeping indivudual grouping as is ?

**Comment by mariapaola5** [comment]
great, thanks.yes for individual.
