### ISSUE TITLE
graph with % from each income with boxplot

### ISSUE THREAD

**Issue by grlurton** [grlurton/DRC_HRH#25]
by province / cadre

**Comment by mariapaola5** [comment]
@grlurton -- you seriously called one graph "median income distribution" and the other "income median distribution" ?!?!?!? you must really hate me... 

a part from that: "median income distribution" (hint: the one with %) is not particularly nice... 
- could you flip the axes so to have USD in vertical and cadre in horizontal? 
- could you also make the USD scale bigger so differences can be seen also for lower incomes? (i.e. taller bars)
- could you change "wage" into "salaire"
- minor tweaks: could you change order to have salaire, prime de risque, prime locale, heures sup, etc (same order).
- colors are awful, and bars too fat.. but i guess not a major deal :-)

btw -- i think it's sweet sweet graph. at last, indeed! 
- could you do me a table with the same info and both median USD amount and %? (wait... will open another issue)
