### ISSUE TITLE
tables for Rishma

### ISSUE THREAD

**Issue by mariapaola5** [grlurton/DRC_HRH#30]
prepare and send table to Rishma: 

find mock tables in Drive / output / tables for joint report_WB

It's just a quick draft. Makes sense? is that what we had agreed on with her? -- stuff highlighted in yellow is for you/to be discussed... I don't think it should take long to do, but Rishma may have questions/ask for other stuff.

**Comment by mariapaola5** [comment]
@grlurton   see the mock tables on Drive.
- nicer to send in Excel as she likely doesn't have github
- i would also say it may be easier to send tables as in the excel format i sent (two-way), rather then the github one way tables. But up to you to decide on this
- remember that she needs data only for staff in CS+CSR!! no HGR, so you'll likely have to rerun some stuff -- could you also update the sampling table?
- on amounts: are you planning to send her averages or median?

**Comment by grlurton** [comment]
Ok done except table 4 we should discuss

took average for aggregates

**Comment by mariapaola5** [comment]
@grlurton 
 i think i spotted a couple of potential issues:
- there may be a mistake with the "cadre" labels. I think the correct order is the one in the "sample" sheet and that the other ones should be changed so that the same ordering (admin, autre, etc.) applies... Could you double check? 
- in the list of incomes, I can't see "private practice" and "informal incomes" (both for number_getting and amounts_received). Could you add them? But there's still "autres" which I would take out if it's only support from other family members.

**Comment by grlurton** [comment]
ordering : nope it's ok, but sample came from indiv table in which I didn't make Cadre into ordered factor. changing it in xls directly

ok didn't interpret right. only autres = non health. didn't add informal as they won't have it ? changing autres into non health act
