### ISSUE TITLE
Check education levels

### ISSUE THREAD

**Issue by grlurton** [grlurton/DRC_HRH#32]
Les medecins apparaissent deux fois...

**Comment by mariapaola5** [comment]
@grlurton I re-checked amounts (you mentioned there was a bug) and also looked for this issue with med. I don't understand how you addressed it: did you group doctor (generalist + specialist) together with pharmacists+etude sup? I thought we had said it should be two different categories, but at this point, no big deal !

**Comment by grlurton** [comment]
@mariapaola5 yep this doctor + pharm + etud sup was the grouping we finally settled for

Can change it if you wish
