### ISSUE TITLE
heat maps on mecanisé and immatriculé

### ISSUE THREAD

**Issue by mariapaola5** [grlurton/DRC_HRH#33]
@grlurton  Analysis of mecanises and immatricules should be the "heat map status" graphs, right? 
You mentioned yesterday that there may be some mistakes (you have no pharmacists in Bandundu...), and the mecanisé stuff looks different from what we had before (linked to issue #16 ??)
Also, remember to do it using the cadre grouping that we agreed on: #18 
Let me know once these are done and which folder/title the tables will have so I can paste them in the ppt.

At this point, don't worry about issues #2 and #3 ...

**Comment by grlurton** [comment]
Differences come from differences in grouping. Comparable groupings with previous analysis are ok.

heat map status is the place to look for it indeed
