### ISSUE TITLE
Penurie & plethore graphs

### ISSUE THREAD

**Issue by mariapaola5** [grlurton/DRC_HRH#34]
@grlurton I am updating the graphs in the ppt and have some questions/issues
- Penurie (staffing_heatmap): there's something weird in the HGR. Maybe when updating the cadre gruping for the pharmacists, you forgot the slightly different categories of personnel for HGR (autre tech and non qualif disappeared...). Could you check? 
  The rest looks fine but of course I am now panicking that there may a whole lot of such little mistakes that I am missing ... :-|
- Pletore for HGR: similar issue? autre tech and non-qual disappeared, and there are weird data on autre (should be "non qual") and infirmier -- the normes line is not correct and there's no one plethorique, while there should be. For the time being, I am keeping the old graph, which looked better (the only issue there is with Pharmacists -- now we want to separate pharmacists from preposés, if possible)

**Comment by grlurton** [comment]
found the bug in hgr

added autre tech

still a few thing to add right now
