### ISSUE TITLE
Recall period for prime partenaire and per diems

### ISSUE THREAD

**Issue by mariapaola5** [grlurton/DRC_HRH#36]
- what is the recall period for per diems and for p.partenaire in the frequency tables? 
- I think you are right, the results for the model are ugly.. what else could be done about it? Maybe it be better if we use the logistics model instead of the “counting” one?
  What is fac_number_appui.csv file I saw in the output? useful? what about the stuff you had done on appui in the analysis online page? -- NOT URGENT -- just trying to get some ideas on how to improve this bit in the report, as all will be looking at it!

**Comment by grlurton** [comment]
@mariapaola5 
not sure what you mean for recall period for per diems in the frequency tables ? I took the data in individual interviews, so with their recall period (3 months)

on the second point, let's discuss it, it all depends on what you want to say

**Comment by mariapaola5** [comment]
great, thanks -- that's what i was wondering: 3 months for per diems, last month for p.practice. but in the total monthly amounts you divided by 3 for per diems, right?

**Comment by grlurton** [comment]
right

De : mariapaola5 [mailto:notifications@github.com]
Envoyé : Friday, January 16, 2015 12:32 AM
À : grlurton/DRC_HRH
Cc : Gregoire Lurton
Objet : Re: [DRC_HRH] Recall period for prime partenaire and per diems (#36)

great, thanks -- that's what i was wondering: 3 months for per diems, last month for p.practice. but in the total monthly amounts you divided by 3 for per diems, right?
