### ISSUE TITLE
table with MCZ incomes by province

### ISSUE THREAD

**Issue by mariapaola5** [grlurton/DRC_HRH#38]
- could I have a table of the MCZ incomes by province, so I can calculate % for each income to use in the narrative. Thanks.
- hey, you used averages, and not medians!! Why? (just for my understanding..)

**Comment by grlurton** [comment]
@mariapaola5 you can it on https://github.com/grlurton/DRC_HRH/blob/master/output/tables/mcz_revenue.csv

using averages because simpler, not a lot of people and distribution ok
