### ISSUE TITLE
pictures for policy brief

### ISSUE THREAD

**Issue by mariapaola5** [grlurton/DRC_HRH#43]
@grlurton  could you select 4 nice/interesting pictures of health centres, maybe with people in them, which i can use in the policy brief? If you don't have time to select them, you can either send 10 random ones, or tell me where i find them all.

**Comment by grlurton** [comment]
@mariapaola5  just put a selection of 18 in Drive\HRH_DRC\pictures_selection from which you can pick

If there are some you want I didn't pick just tell me !
