### ISSUE TITLE
analysis on difference salaries / mecanises

### ISSUE THREAD

**Issue by grlurton** [grlurton/DRC_HRH#5]
juste premiere difference par province, au niveau national, type de cente de sante

**Comment by mariapaola5** [comment]
@grlurton what you could do for this is a heatmap/table comparing mecanisation and salary payment. something like:
![image](https://cloud.githubusercontent.com/assets/10389217/5738324/55b26b7e-9beb-11e4-9e7e-5271ff7807eb.png)

Also good if you give me % at national level and by prov for the narrative. Thanks.

**Comment by grlurton** [comment]
some differences come from modification of staff categories in the data. Otherwise, checked, numbers are ok

additional heatmap in heat_maps_status and in table comparison_immatricule_mecanise

**Comment by mariapaola5** [comment]
@grlurton   Looks great -- but I did mean a comparison of mécanisés and SALARIéS (those receiving a salary) which was the title of the issue.. feasible?
Also, as mentioned, can I get row data of % of salariés nationally, and by prov (X% in S. Kivu, etc.)- Thanks.
